spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:umbral}
    username: ${DB_USER:umbral_user}
    password: ${DB_PASSWORD:umbral_password}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

umbral:
  app:
    cors:
      allowed-origins: http://localhost:8080
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
      allowed-headers: Content-Type,Authorization,X-Requested-With
      allow-credentials: true
      max-age: 3600
  smtp:
    web:
      url: http://localhost:8080
  email:
    confirmation:
      expiration: 604800000
  jwt:
    issuer: https://umbral.codesoftlabs.com
    access:
      secret: dev-access-secret-only-for-local-use-replace-in-prod
      expiration: 5m
    refresh:
      secret: dev-refresh-secret-only-for-local-use-replace-in-prod
      expiration: 30d

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

server:
  port: 8080
